{% set name = "sos-matlab" %}
{% set version = "0.18.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 93e7ca65de150732aeb18f8a27d08758554d7c0f5047532143158acc9ce908b3

build:
  noarch: python
  number: 0
  script:
    - python -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - sos-notebook >=0.23.2
    - scipy
    - numpy
    - pandas
    - python >=3.6

outputs:
  - name: sos-matlab
    test:
      imports:
        - sos_matlab
  - name: sos-octave
    requirements:
      run:
        - {{ pin_subpackage('sos-matlab', exact=True) }}
        - octave
        - octave_kernel
    test:
      requires:
        - nose
        - pytest
        - selenium
        - jupyter_contrib_nbextensions >=0.5.1
      imports:
        - sos_matlab
      commands:
        - python test_octave.py
      files:
        - test_octave.py

about:
  home: https://github.com/vatlab/sos-matlab
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: SoS language module for MATLAB and Octave
  doc_url: https://vatlab.github.io/sos-docs/
  dev_url: https://github.com/vatlab/sos-matlab

extra:
  recipe-maintainers:
    - BoPeng
